import Head from 'next/head'
import {useState} from 'react'
import styles from '../styles/Home.module.css'
import {Button, List} from 'antd'
import CustomerModal from '../components/customerModal/component'


export default function Home() {

  const [isModalOpen,setIsModalOpen] = useState(false);
  const [customers, setCustomers] =  useState([]);

  function toggleModal(){
    setIsModalOpen(!isModalOpen);
  }

  function handleSubmitCustomer(formData){

    // save to database

    // SAVE TO LOCAL STATE
    // clone list
    const clonedCustomers = [...customers];
    const userData = {
      customerName: formData.customerName,
      phoneNumber: formData.phone
    } 
    clonedCustomers.push(userData);
    setCustomers(clonedCustomers)

    // close modal
    toggleModal();
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <Button onClick={toggleModal}>Create customer</Button>
        <CustomerModal isModalOpen={isModalOpen} onToggleModal={toggleModal} handleSubmitCustomer={handleSubmitCustomer}/>
        <CustomersList customerData={customers}/>
      </main>
    </div>
  )
}

function CustomersList({customerData}){
  return(
    <List
    itemLayout="horizontal"
    dataSource={customerData}
    renderItem={item => (
      <List.Item>
        <List.Item.Meta
          title={item.customerName}
          description={item.phoneNumber}
        />
      </List.Item>
    )}
  />
  )
}

